/* eslint-disable @typescript-eslint/no-require-imports -- CommonJS test harness supports runner-provided NODE_PATH dependencies. */
/* Run against npm run start -- --port 3105. Playwright may be supplied by NODE_PATH.
   No server integration is claimed: API routes below are contract mocks. */
const {selectScenario} = require('./browser-helpers.cjs');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const ts = require('typescript');
const Module = require('node:module');
const fixtureModule = new Module(path.resolve('src/components/dashboard/fixtures.ts'));
fixtureModule._compile(ts.transpileModule(fs.readFileSync(fixtureModule.id, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, fixtureModule.id);
const fixture = fixtureModule.exports;
if (fs.existsSync('.env.local')) process.loadEnvFile('.env.local');
const base = process.env.UI_BASE_URL || 'http://localhost:3105';
const launch = process.env.UI_BROWSER_CHANNEL ? { channel: process.env.UI_BROWSER_CHANNEL } : {};
async function visible(locator) { await locator.waitFor({ state: 'visible' }); }
(async () => {
  const browser = await chromium.launch({ ...launch, headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  let checks = 0;
  const pass = name => { checks++; console.log(`PASS ${name}`); };
  try {
    assert.ok(process.env.ADMIN_PASSWORD, 'Set ADMIN_PASSWORD for the test server');
    assert.equal((await page.request.post(base + '/api/auth/session', {data:{username:process.env.ADMIN_USERNAME || 'admin',password:process.env.ADMIN_PASSWORD}})).status(),200);
    await page.goto(base); await page.waitForURL('**/history');
    await page.getByRole('link',{name:'Обзор',exact:true}).click();
    await visible(page.getByRole('heading', { name: /Энергия завтрашнего дня|Прогноз на 48 часов/ }));
    await visible(page.getByRole('img', { name: /Почасовой прогноз/ }));
    assert.equal(await page.locator('html').getAttribute('lang'), 'ru');
    fs.mkdirSync('.next/ui-qa', { recursive: true });
    await page.screenshot({ path: '.next/ui-qa/overview.png', fullPage: true });
    pass('Russian overview and root redirect');
    await page.getByRole('link', { name: 'Прогноз', exact: true }).click();
    await visible(page.getByRole('img', { name: /Почасовой прогноз на 48/ }));
    await page.getByRole('button', { name: 'Таблица', exact: true }).click();
    assert.equal(await page.locator('tbody tr').count(), 48);
    await page.getByLabel('Горизонт', { exact: true }).selectOption('24');
    assert.equal(await page.locator('tbody tr').count(), 24);
    await page.getByLabel('Выпуск / версия').selectOption('demo-backtest-v1');
    if (!(await page.locator('.forecast-details').evaluate(el => el.open))) await page.locator('.forecast-details summary').click();
    await visible(page.getByText('demo-backtest-v1', { exact: true }));
    pass('forecast horizon, versions and table');
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /Экспорт CSV/ }).click()]);
    assert.match(download.suggestedFilename(), /^DEMO-/);
    const csv = fs.readFileSync(await download.path(), 'utf8');
    assert.match(csv, /forecast_run_id/); assert.equal(csv.split('\r\n').length, 49);
    pass('CSV exports entire immutable version with metadata');
    await page.getByLabel('Часовой пояс', { exact: true }).selectOption('Asia/Almaty');
    await visible(page.locator('caption').filter({ hasText: 'Asia/Almaty' }));
    await page.getByLabel('Режим', { exact: true }).selectOption('replay');
    await visible(page.getByText('СИМУЛЯЦИЯ · REPLAY', { exact: true }));
    if (!(await page.locator('.forecast-details').evaluate(el => el.open))) await page.locator('.forecast-details summary').click();
    await visible(page.getByText('demo-replay-v2', { exact: true }));
    await page.getByLabel('Режим', { exact: true }).selectOption('live');
    if (!(await page.locator('.forecast-details').evaluate(el => el.open))) await page.locator('.forecast-details summary').click();
    await visible(page.getByText('demo-live-v2', { exact: true }));
    pass('explicit timezone and isolated replay/live data');
    for (const [scenario, text] of [['stale', 'Устаревшие данные.'], ['partial', 'Частичные данные:'], ['empty', 'Пока нет данных'], ['error', 'Демонстрация ошибки:'], ['loading', 'Загружаем данные…']]) {
      await selectScenario(page, scenario);
      await visible(page.getByText(text, { exact: false }).first());
    }
    await selectScenario(page, 'ready');
    await page.getByLabel('Режим', { exact: true }).selectOption('backtest');
    await visible(page.getByRole('img', { name: /Почасовой прогноз/ }));
    await page.getByRole('button', { name: 'Запустить бэктест', exact: true }).click();
    await visible(page.getByText('demo-forecast-job', { exact: true }));
    await page.getByRole('button', { name: 'Открыть отчёт', exact: true }).click();
    await visible(page.getByRole('heading', { name: /Отчёт оценки/ }));
    pass('all five resource states, job acceptance and evaluation report');
    await page.getByRole('link', { name: 'Источники', exact: true }).click();
    await page.locator('input[type=file]').setInputFiles({ name: 'sample.csv', mimeType: 'text/csv', buffer: Buffer.from('time,wind,power,temp\n2026-01-01 0:00:00,5.5,0.3,-2\n') });
    await visible(page.getByRole('columnheader', { name: 'time', exact: true }));
    for (const [label, column] of [['Время','time'], ['Скорость ветра · м/с','wind'], ['Нормализованная мощность · исходная шкала','power'], ['Температура · °C','temp']]) await page.getByLabel(label, { exact: true }).selectOption(column);
    await page.getByLabel('Исходный часовой пояс', { exact: true }).selectOption('UTC');
    await page.getByLabel('Смысл метки времени', { exact: true }).selectOption('interval_start');
    assert.equal(await page.getByRole('button', { name: 'Проверить демосценарий импорта' }).isDisabled(), true);
    await page.getByLabel('Основание доступности данных').fill('Available after interval');
    await page.getByRole('checkbox').check();
    await page.getByRole('button', { name: 'Проверить демосценарий импорта' }).click();
    await visible(page.getByRole('heading', { name: 'Отчёт импорта · demo-import' }));
    await page.getByLabel('Скорость ветра · м/с', { exact: true }).selectOption('power');
    await visible(page.getByText('Каждому полю нужна отдельная колонка CSV.'));
    assert.equal(await page.getByRole('checkbox').isChecked(), false);
    await page.screenshot({ path: '.next/ui-qa/sources.png', fullPage: true });
    pass('CSV preview, mapping, confirmation invalidation and import report');
    await page.locator('#connector-oracle').getByRole('button',{name:'Проверить доступ',exact:true}).click();
    await visible(page.getByText('Доступ подтверждён',{exact:true}).first());
    await page.getByLabel('Oracle · исторические данные · Поле времени').selectOption('EVENT_TIME');
    await page.getByLabel('Oracle · исторические данные · Поле мощности').selectOption('ACTIVE_POWER_NORM');
    await page.locator('#connector-oracle').getByRole('button',{name:'Включить загрузку истории',exact:true}).click();
    await visible(page.locator('#connector-oracle').getByText('Шлюз принял настройку подключения',{exact:true}));
    await page.getByRole('button',{name:'Проверить доступ',exact:true}).last().click();
    await page.getByLabel('Siemens WinCC · текущие данные · Тег мощности').selectOption('TURBINE_01.ActivePower');
    await page.getByLabel('Siemens WinCC · текущие данные · Тег скорости ветра').selectOption('TURBINE_01.WindSpeed');
    await page.getByRole('button',{name:'Включить получение обновлений',exact:true}).click();
    await visible(page.locator('#connector-wincc').getByText('Шлюз принял настройку подключения',{exact:true}));
    pass('Oracle history and Siemens WinCC live connector workflows');
    await page.getByRole('link', { name: 'Журнал агента', exact: true }).click();
    await visible(page.getByRole('heading', { name: 'Загрузка погоды' }));
    assert.equal(await page.locator('.timeline li').count(), 4);
    await page.getByRole('link', { name: 'Открыть результат →' }).click();
    if (!(await page.locator('.forecast-details').evaluate(el => el.open))) await page.locator('.forecast-details summary').click();
    await visible(page.getByText('demo-backtest-v2', { exact: true }));
    pass('agent steps and result navigation');
    await page.getByLabel('Данные', { exact: true }).selectOption('api');
    await visible(page.getByRole('alert').first());
    assert.equal(await page.getByRole('img', { name: /Почасовой прогноз/ }).count(), 0);
    pass('real unconfigured API yields error without synthetic fallback');
    let failForecast = false; let sparseForecast = false; let zeroPairs = false; const requests = [];
    await page.route('**/api/v1/**', async route => {
      const req = route.request(); const url = new URL(req.url()); requests.push({ path: url.pathname, method: req.method(), body: req.postData(), headers: req.headers() });
      let data;
      if (url.pathname === '/api/v1/assets') data = fixture.assets;
      else if (url.pathname === '/api/v1/forecasts') { if (failForecast) return route.fulfill({ status: 503, body: 'private stack must not display' }); data = fixture.forecasts(url.searchParams.get('mode'), 'ready'); if (sparseForecast) data[0].points.splice(8, 1); }
      else if (url.pathname === '/api/v1/backtest-jobs') data = { job_id: 'api-job-1' };
      else if (url.pathname === '/api/v1/jobs/api-job-1') data = { id:'api-job-1', status:'succeeded', progress:1, result_id:'api-evaluation', error:null };
      else if (url.pathname.startsWith('/api/v1/evaluations/')) data = zeroPairs ? { ...fixture.evaluation, n:0, mae:0, rmse:0, baseline_mae:0, coverage:0 } : fixture.evaluation;
      else if (url.pathname === '/api/v1/connections') data = fixture.connections;
      else if (url.pathname === '/api/v1/imports' && req.method() === 'POST') data = { id:'api-import-report' };
      else if (url.pathname === '/api/v1/imports/api-import-report') data = { ...fixture.report, id:'api-import-report' };
      else return route.fulfill({ status:404, body:'unknown' });
      await route.fulfill({ status:req.method() === 'POST' ? 202 : 200, contentType:'application/json', body:JSON.stringify(data) });
    });
    await page.getByLabel('Данные', { exact: true }).selectOption('fixture');
    await page.getByLabel('Данные', { exact: true }).selectOption('api');
    await visible(page.getByRole('img', { name: /Почасовой прогноз/ }));
    failForecast = true;
    await page.getByRole('button', { name: '↻ Обновить', exact: true }).click();
    await visible(page.getByRole('alert').filter({ hasText:'HTTP 503' }));
    await visible(page.getByRole('img', { name: /Почасовой прогноз/ }));
    await visible(page.getByText('Устаревшие данные.', { exact:false }));
    assert.equal(await page.getByText('private stack must not display').count(), 0);
    pass('failed refresh retains last success and masks raw server error');
    failForecast = false; sparseForecast = true;
    await page.getByRole('button', { name:'Повторить', exact:true }).click();
    await visible(page.getByText('Частичные данные:', {exact:false}));
    assert.equal((await page.locator('path.prediction').getAttribute('d')).split('M').length - 1, 2);
    pass('omitted hourly point creates a chart gap rather than fabricated continuity');
    await page.getByLabel('Момент выпуска (UTC)').fill('2026-01-31T12:00');
    await page.getByLabel('Разрешённая версия модели').fill('approved-model');
    await page.getByRole('button', { name:'Запустить бэктест', exact:true }).click();
    await visible(page.getByText('api-job-1', { exact:true }));
    const posted = requests.find(req => req.path === '/api/v1/backtest-jobs');
    assert.equal(JSON.parse(posted.body).mode, 'backtest'); assert.equal(JSON.parse(posted.body).issued_at, '2026-01-31T12:00:00.000Z'); assert.ok(posted.headers['idempotency-key']);
    zeroPairs = true;
    await page.getByLabel('Идентификатор оценки').fill('zero-pairs');
    await page.getByRole('button', { name:'Открыть отчёт', exact:true }).click();
    await visible(page.getByRole('heading', { name:/Отчёт оценки/ }));
    assert.equal(await page.locator('.report .metric strong').filter({ hasText:'Нет данных' }).count(), 3);
    pass('API job request uses UTC and idempotency key; N=0 is not zero error');
    await page.getByRole('link', { name:'Источники', exact:true }).click();
    await page.locator('input[type=file]').setInputFiles({ name:'api.csv', mimeType:'text/csv', buffer:Buffer.from('t,w,p,c\n2026-01-01,3,0.2,1') });
    for (const [label,column] of [['Время','t'],['Скорость ветра · м/с','w'],['Нормализованная мощность · исходная шкала','p'],['Температура · °C','c']]) await page.getByLabel(label,{exact:true}).selectOption(column);
    await page.getByLabel('Исходный часовой пояс',{exact:true}).selectOption('UTC');
    await page.getByLabel('Смысл метки времени',{exact:true}).selectOption('interval_end');
    await page.getByLabel('Основание доступности данных').fill('Available after interval');
    await page.getByRole('checkbox').check();
    await page.getByRole('button',{name:'Загрузить и проверить',exact:true}).click();
    await visible(page.getByRole('heading',{name:'Отчёт импорта · api-import-report'}));
    const imported = requests.find(req => req.path === '/api/v1/imports' && req.method === 'POST');
    assert.match(imported.headers['content-type'], /multipart\/form-data/); assert.match(imported.body, /interval_end/); assert.match(imported.body, /"normalizedPower":"p"/);
    pass('API import posts file, mapping and explicit source options, then retrieves report');
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.screenshot({path:'.next/ui-qa/mobile.png',fullPage:true});
    assert.deepEqual(errors,[]);
    pass('mobile layout has no page overflow; no browser runtime errors');
    console.log(`${checks} UI scenarios passed.`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
