/* eslint-disable @typescript-eslint/no-require-imports -- Playwright supplied by runner. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('playwright');
if (fs.existsSync('.env.local')) process.loadEnvFile('.env.local');
const base = process.env.UI_BASE_URL || 'http://localhost:3107';
(async () => {
  assert.ok(process.env.ADMIN_PASSWORD, 'Set ADMIN_PASSWORD for the test server');
  const browser = await chromium.launch({ headless:true, ...(process.env.UI_BROWSER_CHANNEL ? {channel:process.env.UI_BROWSER_CHANNEL} : {}) });
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage(); page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  let checks=0;const pass=name=>{checks++;console.log('PASS '+name);};
  fs.mkdirSync('.next/ui-qa',{recursive:true});
  try {
    for(const route of ['/','/history','/overview','/forecast?run=private','/sources','/agent-log']) {
      const response=await context.request.get(base+route,{maxRedirects:0});
      assert.equal(response.status(),307);assert.match(response.headers().location,/\/login\?next=/);
      assert.doesNotMatch(await response.text(),/baseline-demo-1/);
    }
    assert.equal((await context.request.get(base+'/api/v1/assets')).status(),401);
    assert.equal((await context.request.get(base+'/api/auth/session')).status(),401);
    pass('server blocks pages and API before authentication');
    await page.goto(base+'/forecast');
    await page.getByRole('status',{name:'Запуск Terra'}).waitFor();
    await page.screenshot({path:'.next/ui-qa/entrance.png'});
    await page.getByRole('status',{name:'Запуск Terra'}).waitFor({state:'hidden',timeout:3500});
    assert.equal(await page.locator('html').getAttribute('lang'),'ru');
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    await page.screenshot({path:'.next/ui-qa/login-light.png',fullPage:true});
    await page.getByLabel('Пароль администратора',{exact:true}).fill('incorrect-password');
    await page.getByRole('button',{name:'Войти',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'Неверный пароль'}).waitFor();
    assert.match(page.url(),/\/login\?/);
    const denied=await context.request.post(base+'/api/auth/session',{data:{username:process.env.ADMIN_USERNAME || 'admin',password:process.env.ADMIN_PASSWORD},headers:{Origin:'https://foreign.test'}});assert.equal(denied.status(),403);
    pass('Russian default, entrance animation and invalid credentials');
    await page.getByLabel('Язык интерфейса').selectOption('en');
    await page.getByRole('alert').filter({hasText:'Incorrect password'}).waitFor();
    await page.getByRole('button',{name:'Switch to dark theme'}).click();
    await page.reload();await page.locator('.launch-screen').waitFor({state:'hidden'});
    assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
    await page.screenshot({path:'.next/ui-qa/login-dark.png',fullPage:true});
    pass('language and theme persist across server renders');
    await page.getByLabel('Administrator password',{exact:true}).fill(process.env.ADMIN_PASSWORD);
    await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/forecast');
    await page.getByRole('img',{name:/Hourly forecast/}).waitFor();
    const cookie=(await context.cookies()).find(item=>item.name==='terra_admin_session');
    assert.ok(cookie?.httpOnly);assert.equal(cookie.sameSite,'Strict');
    assert.equal((await context.request.get(base+'/api/auth/session')).status(),200);
    await page.getByRole('button',{name:'Table',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),48);
    pass('real session sign in returns to requested page; forecast remains functional');
    for(const [route,heading] of [['/history','Historical run'],['/overview','48-hour forecast'],['/forecast','Generation forecast'],['/sources','Data sources'],['/agent-log','Agent log']]){
      await page.goto(base+route);await page.locator('.launch-screen').waitFor({state:'hidden'});
      await page.getByRole('heading',{name:heading,exact:true}).waitFor();
      await page.waitForFunction(()=>!document.querySelector('.loading'));
      const content=await page.locator('main').innerText();
      assert.doesNotMatch(content,/[А-Яа-яЁё]/,route+' untranslated copy');
    }
    pass('all five dashboard pages translated into English');
    await page.getByLabel('Interface language').selectOption('kk');
    await page.getByRole('link',{name:'Шолу',exact:true}).click();
    await page.getByRole('heading',{name:'48 сағаттық болжам'}).waitFor();
    await page.getByRole('img',{name:/сағатқа арналған болжам/}).waitFor();
    await page.screenshot({path:'.next/ui-qa/overview-kazakh-dark.png',fullPage:true});
    pass('Kazakh navigation, dates and forecast labels');
    await page.getByLabel('Интерфейс тілі').selectOption('ru');
    await page.getByRole('button',{name:'Включить светлую тему'}).click();
    await page.getByRole('img',{name:/Почасовой прогноз/}).waitFor();
    await page.screenshot({path:'.next/ui-qa/overview-light.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.getByRole('button',{name:'Открыть меню'}).click();
    await page.getByRole('link',{name:'Источники',exact:true}).click();
    assert.equal(await page.locator('.app-shell').getAttribute('class'),'app-shell ');
    await page.waitForFunction(()=>!document.querySelector('.loading'));
    await page.screenshot({path:'.next/ui-qa/mobile-sources.png',fullPage:true});
    pass('mobile menu and layout');
    await page.emulateMedia({reducedMotion:'reduce'});
    assert.equal(await page.locator('.rotor').count(),0);
    await page.getByRole('button',{name:'Выйти',exact:true}).click();await page.waitForURL('**/login');
    assert.equal((await context.request.get(base+'/overview',{maxRedirects:0})).status(),307);
    assert.equal(await page.locator('.rotor').first().evaluate(el=>getComputedStyle(el).animationName),'none');
    pass('logout removes access and reduced motion stops turbines');
    await context.addCookies([{name:'terra_admin_session',value:'admin.9999999999.'+'0'.repeat(64),url:base}]);
    assert.equal((await context.request.get(base+'/forecast',{maxRedirects:0})).status(),307);
    assert.deepEqual(errors,[]);
    pass('forged session fails closed; no browser runtime errors');
    const {createHmac}=require('node:crypto');
    const body='admin.'+(Math.floor(Date.now()/1000)-60);
    const expired=body+'.'+createHmac('sha256',process.env.SESSION_SECRET).update(body).digest('hex');
    await context.addCookies([{name:'terra_admin_session',value:expired,url:base}]);
    assert.equal((await context.request.get(base+'/overview',{maxRedirects:0})).status(),307);
    await context.request.post(base+'/api/auth/session',{data:{username:process.env.ADMIN_USERNAME || 'admin',password:process.env.ADMIN_PASSWORD}});
    await page.goto(base+'/overview');await page.locator('.launch-screen').waitFor({state:'hidden'});
    await context.clearCookies({name:'terra_admin_session'});
    await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
    await page.waitForURL('**/login?next=*');
    pass('expired sessions and expiry in an open dashboard return to sign in');
    console.log(`${checks} platform scenarios passed.`);
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
